language: rust
sudo: required
dist: trusty

before_cache:
  - cargo install cargo-tarpaulin

cache: cargo

script:
  - cargo clean
  - cargo build
  - cargo test

after_success:
  - cargo tarpaulin --exclude-files src/proto/* --exclude-files tests/* --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
