[package]
name = "cwl"
version = "0.1.0"
authors = ["Onno Valkering"]
edition = "2018"

[dependencies]
failure = "0.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.3"
serde_yaml = "0.8"