name: Coverage
on:
  pull_request:    
  push:
    branches:
      - master

jobs:
  tarpaulin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--avoid-cfg-tarpaulin --workspace'
          out-type: 'Lcov'

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
